### ISSUE TITLE
Initial commit & readme

### ISSUE THREAD

**Issue by alce65** [AlinaLaurs/202210-W3CH5-Alina-Laurs#2]
Hola Alina.
Está muy bien incluir en el readme las instrucciones del challenge, pero si dejas una imagen, asegúrate de que el enlace sea correcto, incluyendo la imagen en el commit inicial.
El readme es la presentación del proyecto y la tuya como developer.
Si está mal, no está invitando a seguir mirando nada dentro del proyecto.
Cámbialo cuando puedas y tenlo en cuenta en el futuro

**Comment by AlinaLaurs** [comment]
Hola Alejandro.
¡Listo! Muchas gracias, lo tendré en cuenta.
Un saludo

**Comment by alce65** [comment]
De nada. Muy bien, cierro el issue
